### PR TITLE
Remove base64url dependency

### PR DESCRIPTION
**Pull request by mworrell**
Remove the dependency on the base64url repository.
This makes Hex packaging easier.

### CODE REVIEW

**Comment by mworrell** [comment]
Closed as this repo is abandoned, we forked to https://github.com/erlangpack/termit

**Comment by dvv** [comment]
Good.

**Comment by mworrell** [comment]
Hi @dvv, good to hear from you!   Are you ok with us publishing your project to hex?  Do you want to have some merge requests?  As nothing happened here for some time, we assumed that you didn't have time for maintenance anymore...

**Comment by dvv** [comment]
Hi @mworrell, I'm certainly ok with that. You guessed quite right. Please go ahead.
--V

**Comment by dvv** [comment]
I mentioned new library location in the original README so people could find the actual fork.

**Comment by mworrell** [comment]
Thanks for the quick response. ErlangPack is maintained by a couple of people. The goal is taking care of "orphaned" repositories that are in active use and need some (small) maintenance now and then.

**Pull request closed without merging**
